# CI for Ad Service

name: ad-ci

on:
    push:
        branches:
          - main

permissions:
  contents: write

jobs:
  local-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install java-jdk-21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Build image locally
        run: |
          mkdir -p proto
          cp ./pb/* proto/
          chmod +x ./gradlew
          ./gradlew installDist -PprotoSourceDir=./proto
          export AD_PORT=8080
          export FEATURE_FLAG_GRPC_SERVICE_ADDR=featureflagservice:50053
         # ./build/install/opentelemetry-demo-ad/bin/Ad

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ad:${{github.run_id}}


  update-k8s-manifest:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update tag in kubernetes deployment manifest
        run: | 
           sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/ad:${{github.run_id}}|" kubernetes/deploy.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git add .
          git commit -m "[CI]: Update product catalog image tag"
          git push origin HEAD:main
